name: HGOChatManager
version: 1.2
main: org.hurricanegames.chatmanager.ChatManagerPlugin
api-version: 1.13
depend:
- Vault
softdepend:
- PlaceholderAPI

commands:
  chatmanageradmin:
    description: ChatManager admin commands
    usage: '/<command>'

permissions:
  hgo.chatmanager.admin:
    description: Admin access
  hgo.chatmanager.chat.unicode:
    description: Use any unicode symbols in chat
    default: op
  hgo.chatmanager.chat.color:
    description: Use color codes in chat
    default: op

website: 'https://github.com/HurricaneGamesOrg/HurricaneGamesOrgChatManager'
authors:
- _Shevchik_
